apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: b82l78kzk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: b82l78kzk-python 
  name: b82l78kzk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: b82l78kzk-python 
